### ISSUE TITLE
why branch

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass2#7] opened 2021-02-02 18:07 UTC
cc: @cyouh95 

@mpatricia01 - assigning this to you, but let me know if you don't have time cuz of other work/class stuff.

I looked over the git branch section. seems like it is missing two things:

1. branches don't come into play until you start using git for collaboration. at present (unless I am missing something), we don't say much about using git for collaboration as opposed to using git as sole user of a repository. therefore, at front of git branch section, strikes me that we should say some practical and conceptual things about using git for collaboration. is there a helpful conceptual figure we can provide? practical rules of thumb?
2. we do have some text on "why use branches" and from there it goes to git branch, merges, and merge conflicts. but I think we should show what happens when two people are working on master branch and both make changes and one person tries to push/pull and they encounter an error. explain this using a practical example. also, after adding this explanation/example, "why branch" should become its own section (would become 8.1)

**Comment by mpatricia01** [comment] 2021-02-04 18:24
@ozanj 

To your point on question 1. I can add a figure about git flow and provide some conceptual things about it. To your point on question 2. it seems that the issue is that we should discuss more why branches should be created and less about creating a new branch for every person. For example, say Crystal and I are both working on different branches and we both make changes to the same sections on the lecture, we will still encounter merge conflicts. My understanding is that branches are created to work on specific things rather than created for every person working on the repo. I think we already cover resolving merge conflicts, but I can add more context as to why create branches in the beginning.

**Closed as completed** 2021-02-18 09:34 UTC
